<!DOCTYPE htm>
<html>

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Alumni Portal</title>
    <link rel="stylesheet" href="style.css">
</head>

<body>

    <div class="interface-header">
        <img src="images/logo.png" alt="PLP Logo" class="logo-interface">
        <div class="text">
            <div class="school-name">Pamantasan Ng Lungsod Ng Pasig</div>
            <p class="p-size">Alkade Jose St. Kapasigan, Pasig City</p>
        </div>
    </div>

    <div class="container">
        <aside class="admin-sidebar">
            <header class="sidebar-header">
                <a href="#" class="header-logo">
                    <img src="images/avatar.PNG" alt="Admin"/>
                </a>
                <button class="toggler">
                    <span><img src="images/hide.PNG"/></span>
                </button>
            </header>
            <nav class="sidebar-nav">
                <ul class="nav-list primary-nav">
                    <li class="nav-item">
                        <a href="#" class="nav-link">
                            <span class="nav-icon"><img src="images/home.PNG"/></span>
                            <span class="nav-label">Home</span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="#" class="nav-link">
                            <span class="nav-icon"><img src="images/gallery.PNG"/></span>
                            <span class="nav-label">Gallery</span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="#" class="nav-link">
                            <span class="nav-icon"><img src="images/home.PNG"/></span>
                            <span class="nav-label">Course List</span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="#" class="nav-link">
                            <span class="nav-icon"><img src="images/alumni_list.PNG"/></span>
                            <span class="nav-label">Alumni List</span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="#" class="nav-link">
                            <span class="nav-icon"><img src="images/jobs.PNG"/></span>
                            <span class="nav-label">Jobs</span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="#" class="nav-link">
                            <span class="nav-icon"><img src="images/home.PNG"/></span>
                            <span class="nav-label">Events</span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="#" class="nav-link">
                            <span class="nav-icon"><img src="images/forums.PNG"/></span>
                            <span class="nav-label">Forums</span>
                        </a>
                    </li>
                </ul>

                <ul class="nav-list secondary-nav">
                    <li class="nav-item">
                        <a href="#" class="nav-link">
                            <span class="nav-icon"><img src="images/log-out.PNG"/></span>
                            <span class="nav-label">Log Out</span>
                        </a>
                    </li>
                </ul>
            </nav>
        </aside>


    </div>

    <main class="content">
        <header>DASHBOARD</header>
        <div class="divisions">
            <div class="alumni">
                <p>0</p> <br>
                <p>Alumni</p>
            </div>
            <div class="forum-topic">
                <p>0</p> <br>
                <p>Forum Topic</p>
            </div>
            <div class="jobs">
                <p>0</p> <br>   
                <p>Jobs</p>
            </div>
            <div class="events">
                <p>0</p> <br>
                <p>Events</p>
            </div>
        </div>
    </main>


</body>

</html>